### ISSUE TITLE
Is original evaluation metric used in cvpr 16 max bbox acc available with this code ?

### ISSUE THREAD

**Issue by graylevel255** [clovaai/wsolevaluation#11]
I needed to evaluate a couple of methods in a fully weakly supervised way without any bbox annotation using the original CVPR 16 metric. Is it possible with this code ?

**Comment by coallaoh** [comment]
I believe (without warranties) that the original CVPR16 metric is identical to our MaxBoxAccV1 (`--box_v2_metric False` in `main.py` arguments) with max normalisation (we use min-max normalisation by default) at a fixed CAM threshold (tau=0.2). 

By using the arguments and adjusting the evaluation code appropriately, you can simulate the original CVPR16 metric.

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
