### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by wenjunbaby** [clovaai/wsolevaluation#13]
I can not obtain the CUBV2 from the prepare_cub.sh.Could you please check  the link valid?

**Comment by coallaoh** [comment]
The link in the shell script `https://onedrive.live.com/download?cid=B7111B95B80CCC66&resid=B7111B95B80CCC66%2130812&authkey=AFMzb4akufUiWU0` works for me.

Are you sure the link is causing the problem?

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
