### ISSUE TITLE
How to do Top-1 localization in your code?

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#14]

**Comment by junsukchoe** [comment]
Currently, we do not provide the evaluation module for top-1 localization. However, you can easily implement the module by modifying our evaluation functions.

**Comment by umairjavaid** [comment]
Can you tell a bit more about how to modify your evaluation functions to get top-1 localization?

**Comment by umairjavaid** [comment]
If you could share some code, that would be really  helpful

**Comment by coallaoh** [comment]
The pseudo-code for top-1 localization is quite straightforward: modify the MaxBoxAcc such that the per-instance success is determined not only by the IoU against the GT box (localization) but also by the correctness of the classification. Please understand that we do not have sufficient manpower to implement every requested code ;)

We may implement the top-1 localization evaluation in the future. When we do so, we will let you know. But again, the code for top-1 localization shouldn't be too complicated or ambiguous to write on top of our evaluation code.

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
