### ISSUE TITLE
What's the range of your threshold values? what is the interval size?

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#16]

**Comment by junsukchoe** [comment]
Hi, 

The range of threshold is [0,1). The interval can be set by ``cam_curve_interval`` (default: .001). Please note the following functions:

https://github.com/clovaai/wsolevaluation/blob/45ac3a1c88551de0d7829131f8e3c66928b37697/evaluation.py#L427

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
