### ISSUE TITLE
Custom datasets

### ISSUE THREAD

**Issue by santoshreddy254** [clovaai/wsolevaluation#17]
Cloud you throw some light on how to modify the code for other custom datasets?
I want to use my own dataset instead of using ImageNet or CUB or OpenImages.
I have dataset in VOC format

**Comment by coallaoh** [comment]
Thank you for your interest in our work.
To add a dataset, prepare the metadata mimicking the file structures and file formats in e.g. https://github.com/clovaai/wsolevaluation/tree/master/metadata/CUB.

You then need to adapt the code to this new dataset by changing e.g.
- https://github.com/clovaai/wsolevaluation/blob/45ac3a1c88551de0d7829131f8e3c66928b37697/config.py#L32
- https://github.com/clovaai/wsolevaluation/blob/45ac3a1c88551de0d7829131f8e3c66928b37697/config.py#L122
- https://github.com/clovaai/wsolevaluation/blob/6692538bc2e396f6076253e814aebea92b12e064/evaluation.py#L468
- https://github.com/clovaai/wsolevaluation/blob/8ca3849134f434ac54a9e98d72b59865f60f459b/inference.py#L63
- https://github.com/clovaai/wsolevaluation/blob/8ca3849134f434ac54a9e98d72b59865f60f459b/main.py#L67

and set the data root (https://github.com/clovaai/wsolevaluation/blob/6692538bc2e396f6076253e814aebea92b12e064/config.py#L136) to your local dataset location.

**Comment by santoshreddy254** [comment]
Very quick response Thank you for that. I will update you if I can do that

**Comment by santoshreddy254** [comment]
Hi,
I am facing issues in how to load VOC format data, you have bounding boxes in a txt file for each image but for me, I have in XML file which is parsed and got the box but I was not able to incorporate in this code. Any help or suggestion is appreciated.

**Comment by coallaoh** [comment]
Sorry, we don't have enough manpower to provide guidance on turning XML files into txt files :(

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
