### ISSUE TITLE
GPU and training time required by this repo

### ISSUE THREAD

**Issue by chenwydj** [clovaai/wsolevaluation#21]
Dear authors,

Thank you very much for this dedicated reop! This is extremely helpful to the WSOL community!

Some questions:
1) Are jobs covered by this repo all only require one GPU to train and evaluate? Is it helpful or necessary to use multiple GPUs?
2) What kind of GPU did you use for the jobs? How much memory did you consume?
3) How much time to train on each dataset?

Thank you again!

**Comment by junsukchoe** [comment]
Thanks for your interest in our work!

1. Yes, we use only one GPU per session. If you use multiple GPUs, you can train the models more quickly. However, you probably need to tune the hyperparameters accordingly. 

2. We used NVIDIA P40 GPU (24Gb VRAM). The memory requirement depends on the dataset, batch size, and methods. For example, on the OpenImages dataset, CAM requires about 4.5Gb memory, and ACoL and SPG need about 6.5Gb memory when the batch size is 32. 

3. Training time depends heavily on the hardware environment. In our environment, CUB experiments take 2-3hours, OpenImages experiments take 6-8 hours, ImageNet (proxy) experiments take 6-8 hours, and ImageNet (full) experiments take 36-48 hours.

I hope this helps you.

**Comment by chenwydj** [comment]
Thank you!
