### ISSUE TITLE
Minor notational inconsistency in paper.

### ISSUE THREAD

**Issue by kdexd** [clovaai/wsolevaluation#24]
This is not directly related to the codebase — I found a very minor consistency in the paper. I am looking at Lemma 3.1 in [arxiv v2](https://arxiv.org/pdf/2001.07437v2.pdf).

![image](https://user-images.githubusercontent.com/10494087/85957931-94efda00-b95f-11ea-945f-9632f8a4637c.png)

You probably meant `M_{bg}` instead of `M_{bf}`, right?

**Comment by coallaoh** [comment]
Thanks a lot for spotting it :)
We will fix it in the next version!

**Comment by kdexd** [comment]
Perfect, thanks!
