### ISSUE TITLE
Cub dataset not downloading. Kindly update the link in your file

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#26]

**Comment by coallaoh** [comment]
Do you mean the CUBV2 dataset? (link: https://drive.google.com/open?id=1U6cwKHS65wayT9FFvoLIA8cn1k0Ot2M1)
It works well for me.
Could you describe the error with more detail?

**Comment by coallaoh** [comment]
I presume you mean this one: https://github.com/clovaai/wsolevaluation/blob/38d4aef1651caf49320abd36fde18540abaf7bfe/dataset/prepare_cub.sh#L3

I believe the original owner of the CUB dataset now serves the dataset with GDrive. The same link (http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/CUB_200_2011.tgz) works, but you need to visit that page using a web browser. You will then be redirected to GDrive and you'll be able to download the dataset.

We will update prepare_cub.sh soon.

**Comment by coallaoh** [comment]
Thank you for your PR!
