### ISSUE TITLE
Test Dataset description

### ISSUE THREAD

**Issue by gowriaddepalli** [clovaai/wsolevaluation#27]
The test dataset for this task describes that the test data contains images with full supervision, but the datasets taken for test  in Imagnet, CUB and open images dont have bounding boxes or masks. Could yo please explain this in detail?

**Comment by junsukchoe** [comment]
Hello,

The localization labels are provided by this github repository. They can be found [here](https://github.com/clovaai/wsolevaluation/tree/master/metadata). 
Please note that you can download mask annotations by using this [shell script](https://github.com/clovaai/wsolevaluation/blob/master/dataset/prepare_openimages.sh) or this [google drive link](https://drive.google.com/open?id=1eu1YvcZlsEalhXTS_5Ni5tkImCliIPie).

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
