### ISSUE TITLE
Doubt regarding input image files in metatdata

### ISSUE THREAD

**Issue by gowriaddepalli** [clovaai/wsolevaluation#32]
The code in the data loader reads the image_ids file as: which has.jpg appended

with open(metadata['image_ids' + suffix]) as f:
        for line in f.readlines():
            image_ids.append(line.strip('\n'))

but while reading open Images data, and reading the localization.txt, it expects. path_file.jpg.npy. isnt it wrong? should it not be path_file.npy. The jpg should be dropped. It would be great if you could clear this issue.

**Comment by coallaoh** [comment]
Thanks for your observation, but I cannot find the specific code fragment you're referring to. 
Can you point to the lines via URLs? 
See https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

**Comment by gowriaddepalli** [comment]
https://github.com/clovaai/wsolevaluation/blob/e00842f8e9d86588d45f8e3e30c237abb364bba4/data_loaders.py#L62

**Comment by junsukchoe** [comment]
Thanks for your interest in our work!

Actually, the `image_id` includes `.jpg`. For example, the score map is located at `{output_path}/123/456.jpg.npy`.
If you have any trouble in this part, please let me know.

**Comment by gowriaddepalli** [comment]
yes, but as per documentation is was just  {output_path}/image1.npy

Apart from that, if you do that, as well, i start getting KeyError: 'image.jpg'
self.mask_paths[image_id],

**Comment by gowriaddepalli** [comment]
I managed to clear the above error. Thanks for your time.
