### ISSUE TITLE
Pretrained Resnet

### ISSUE THREAD

**Issue by shadowwkl** [clovaai/wsolevaluation#37]
Hi,

I notice that for ResNet-50, you change the stride to 1 at _Layer 3_ (the name comes from pytorch, torchvision.models.resnet50), in order to increase the feature map from 7x7 to 14x14. So I wonder do you first do this change and then use ImageNet to train the modified ResNet-50, and finally based on this trained version new ResNet-50, you train (or finetune) it using CUB dataset?

**Comment by junsukchoe** [comment]
Hello,

We did not pre-train our customized networks and just use ImageNet pre-trained models from PyTorch. 
I hope that this reply is helpful!

**Comment by shadowwkl** [comment]
> Hello,
> 
> We did not pre-train our customized networks and just use ImageNet pre-trained models from PyTorch.
> I hope that this reply is helpful!

Hi!

Thanks for your reply. So you keep all the weights from the imagenet-pretrained model except the two last strided conv layers, which originally have stride 2 and now are set to 1 in order to increase the feature map from 7x7 to 14x14. Do I understand correctly?

**Comment by junsukchoe** [comment]
> So you keep all the weights from the imagenet-pretrained model except the two last strided conv layers,

No, we use all weights of ImageNet pretrained model, including the last two strided conv layers.

**Comment by shadowwkl** [comment]
> > So you keep all the weights from the imagenet-pretrained model except the two last strided conv layers,
> 
> No, we use all weights of ImageNet pretrained model, including the last two strided conv layers.

Thank you! Problem solved.
