### ISSUE TITLE
Dataset Structure

### ISSUE THREAD

**Issue by syedsadiqalinaqvi** [clovaai/wsolevaluation#44]
Thank you for putting together this brilliant collection of WSOL methods and shedding light on the reality of the progress in the field! Truly appreciated!
I was trying to run your code on my own custom dataset following the directions from https://github.com/clovaai/wsolevaluation/issues/17 
I was wondering whether the dataset folder hierarchy plays a crucial role in determining class labels. As long as I've correctly produced the `class_labels.txt` file, do I need to care about the subfolders? For example, I've two labels `0` and `1`. Do I need to create two subfolders or putting all the images in one folder should be enough?

**Comment by junsukchoe** [comment]
Thanks for your interest in our work!

You do not need to care about your dataset structure. You can indicate the class by using `csv` format.
Please see https://github.com/clovaai/wsolevaluation/blob/master/metadata/CUB/train/class_labels.txt for the reference.

**Comment by syedsadiqalinaqvi** [comment]
Thanks!
