### ISSUE TITLE
Cropping and Resizing

### ISSUE THREAD

**Issue by syedsadiqalinaqvi** [clovaai/wsolevaluation#45]
Can you please provide any insights on why you crop images in 224x224 patches by default and why you resize them to 256x256, regardless of input image size?

**Comment by junsukchoe** [comment]
It is a common practice in WSOL community for the last four years. There are multiple other pre-processing choices such as random-crop-and-resize, but we stick to the resize-and-crop for the fair comparison.

**Comment by syedsadiqalinaqvi** [comment]
Oh okay, thanks!
