### ISSUE TITLE
optimal oracle value

### ISSUE THREAD

**Issue by wjun0830** [clovaai/wsolevaluation#46]
Hello. Thank you for such interesting work.
I have one question though
I got it that you randomly conducted 30 trials for each method with single backbone.

Then how did you choose the optimal oracle value?
You mentioned that you find it with train-fullsup set.
Do you mean that you have conducted multiple experiments on train-fullsup set to find optimal oracle?

**Comment by junsukchoe** [comment]
Hello,

Thanks for your interest in our work!

Our objective is to evaluate the quality of the score map itself, so we remove the influence of threshold tau. To this end, we find the optimal tau by testing each trained model with all threshold tau [0, 1] on `test-fullsup` split.
