### ISSUE TITLE
Interpretation of the result

### ISSUE THREAD

**Issue by shashankvkt** [clovaai/wsolevaluation#47]
Hi,
Thank you for providing the code for this amazing work. I have a question for which I seek your guidance. When I run the basic resnet50 code for CAM on CUB200, I get the following results on the test set

```
Split test, metric classification, current value: 50.517777010700726
Split test, metric localization, current value: 58.97480151881257
Split test, metric localization_IOU_30, current value: 96.08215395236452
Split test, metric localization_IOU_50, current value: 66.27545736969279
Split test, metric localization_IOU_70, current value: 14.566793234380393
```

I wanted to confirm whether `metric localization` corresponds to the `MaxBoxAcc-v2` metric that you rmention in your work? Also what does `metric localization, current value ` mean?. In Table 6 of your paper, do you report metric localization_IOU_50? Looking forward to hearing from you.
Thanks

**Comment by Jazzcharles** [comment]
I think  `Split test, metric localization, current value` corresponds to the final MaxBoxAcc-v2 score in Table6, which is the average of IOU_30, IOU_50, and IOU_70 as mentioned by the authors.

**Comment by junsukchoe** [comment]
Thank you for your interest in our work!

By default, the `metric localization` means the average of IOU_30, IOU_50, and IOU_70.
Please also note that if you set `box_v2_metric` to `False`, it means IIU_50.

**Comment by shashankvkt** [comment]
Thanks @Jazzcharles and @junsukchoe
