### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'iou_threshold_list' and 'multi_contour_eval'

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#6]
I downloaded the CUB dataset using `bash wsolevaluation/dataset/prepare_cub.sh` comand

Now, I am getting the  error mentioned after running the following commands:
!python evaluation.py --scoremap_root=train_log/scoremaps/ \
                     --metadata_root=metadata/CUB/test \
                     --mask_root=dataset/ \
                     --dataset_name=CUB \
                     --split=val \
                     --cam_curve_interval=0.01

**Comment by junsukchoe** [comment]
Thanks for your interest in our work!

The bug is due to the recent update of box evaluation. We just fixed this bug. 
Regarding the `evaluation.py`, please also refer to #3.
