### ISSUE TITLE
consult training hyperparameters

### ISSUE THREAD

**Issue by shaofeifei11** [clovaai/wsolevaluation#60]
Dear Sir or Madam,

First of all thank you very much for your excellent work. 

I want to follow your work, but I want to consult some training hyperparameters.

Could you give me some training hyperparameters for other models and datasets based on the example training parameters below? (CUB+vgg16_CAM,  CUB+InceptionV3_CAM, CUB+resnet50_CAM, Imagenet+vgg16_CAM,  Imagenet+InceptionV3_CAM,  Imagenet+resnet50_CAM)

```
python main.py --dataset_name CUB \
               --architecture vgg16 \
               --wsol_method cam \
               --experiment_name CUB_vgg16_CAM \
               --pretrained TRUE \
               --num_val_sample_per_class 5 \
               --large_feature_map FALSE \
               --batch_size 32 \
               --epochs 50 \
               --lr 0.00001268269 \
               --lr_decay_frequency 15 \
               --weight_decay 5.00E-04 \
               --override_cache FALSE \
               --workers 4 \
               --box_v2_metric True \
               --iou_threshold_list 30 50 70 \
               --eval_checkpoint_type last
               --norm_method ivr
```
![image](https://github.com/clovaai/wsolevaluation/assets/50863459/f6f9b490-77a4-4578-822d-8fa15828e659)

Best regards

**Comment by SanghyukChun** [comment]
@shaofeifei11 
Hi, can this issue (#22) help you?

**Comment by shaofeifei11** [comment]
Thank you for your timely reply!
Yes, this is what i want. Thank you!

**Comment by shaofeifei11** [comment]
Could you tell the resize value of InceptionV3 and resnet50?

**Comment by SanghyukChun** [comment]
What do you mean for `resize`?
If you mean the input image size, all inputs are the same as 224
https://github.com/clovaai/wsolevaluation/blob/96f4b88679af41f005824661f47e6fe3628af2aa/inference.py#L35

We only searched the following hyperparameters for each method.

<img width="1004" alt="image" src="https://github.com/clovaai/wsolevaluation/assets/4919315/736d1518-e192-41bd-bea1-4f4d1749a507">

If you mean the feature map size, `large_feature_map` TRUE denotes `28x28`, FALSE detnoes `14x14`
https://github.com/clovaai/wsolevaluation/blob/96f4b88679af41f005824661f47e6fe3628af2aa/wsol/vgg.py#L288
