### ISSUE TITLE
About the class of objects

### ISSUE THREAD

**Issue by Breezewrf** [clovaai/wsolevaluation#61]
Hi, 

I wonder why the class label annotated like this:
`001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg,0`

And it is weird, all images in your dataset(CUB, I just downloaded the small one dataset) only include single object? 

I am new to wsod, is it usual to train the model in this style like only detect single object rather than multiple objects?

Thank you for your answer!

**Comment by SanghyukChun** [comment]
https://github.com/clovaai/wsolevaluation/blob/96f4b88679af41f005824661f47e6fe3628af2aa/data_loaders.py#L50-L83

The metadata is csv where each column denotes image id and class name. Hence, `001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg` is the image id, and `0` is the class label.

WSOL only contains a single object, and no object box is provided. We only train a normal classifier and extract heatmaps using some techniques (e.g., CAM). If you would like to work on WSOD, you'd better to search another repository for WSOD (detection), not WSOL (localization)

**Comment by Breezewrf** [comment]
I got it, thanks a lot!
