### ISSUE TITLE
The processing of score maps

### ISSUE THREAD

**Issue by SvyJ** [clovaai/wsolevaluation#62]
Thanks for this amazing work, but could you please provide the code for the score map processing ?

**Comment by SanghyukChun** [comment]
I am not sure about your question, but this code would be helpful
https://github.com/clovaai/wsolevaluation/blob/master/inference.py

**Comment by SvyJ** [comment]
> I am not sure about your question, but this code would be helpful https://github.com/clovaai/wsolevaluation/blob/master/inference.py

**Comment by SvyJ** [comment]
The problem I encountered is how to convert the generated score maps into heat maps (i.e. like cams) for display, you may provide code for this simple problem.

**Comment by SanghyukChun** [comment]
Please check this one. Visualizing CAM is not the scope of this project.
https://stackoverflow.com/questions/33282368/plotting-a-2d-heatmap
