### ISSUE TITLE
ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#7]
Getting the mentioned error by running this command

!python main.py --dataset_name CUB \
               --architecture vgg16 \
               --wsol_method cam \
               --experiment_name CUB_vgg16_CAM \
               --pretrained TRUE \
               --num_val_sample_per_class 5 \
               --large_feature_map FALSE \
               --batch_size 32 \
               --epochs 10 \
               --lr 0.00227913316 \
               --lr_decay_frequency 3 \
               --weight_decay 5.00E-04 \
               --override_cache FALSE \
               --workers 4 \
               --multi_iou_eval False \
               --iou_threshold_list 30 50 70 \
               --multi_contour_eval False \
               --eval_checkpoint_type best

**Comment by coallaoh** [comment]
Try
```
--num_val_sample_per_class 0
```

Some CUBV2 classes have less than 5 samples per class.
