### ISSUE TITLE
where are you doing hyperparameter search?

### ISSUE THREAD

**Issue by umairjavaid** [clovaai/wsolevaluation#8]
As mentioned in the paper, where is the code for hyperparameter search?

**Comment by coallaoh** [comment]
We do not have any code for it. In fact, the random hyperparameter search algorithm is too simple to write a code ;)

You can generate configs (arguments) for `train.py` with your favourite random number generator according to the search space indicated in Table 5 (appendix). For example, we have used the random number generators in Google Sheets to generate the configs. You can also use Numpy random number generators.
